# Generated by Django 2.2.7 on 2019-11-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okstupid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_one',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_three',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_two',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
